apiVersion: batch/v1
kind: Job
metadata:
  name: ml-kube
  namespace: docker-exp-8
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: experiment-one
        image: public.ecr.aws/q1b7b4u6/cedipengineering/docker_ml_ecr:latest
        ports:
        - containerPort: 80
        env:
        - name: MLFLOW_TRACKING_URI 
          value: "http://3.143.228.222:5000" 
        - name: experiment_name 
          value: mlflow_measurement_eks_8_exp
        - name: layersTypes 
          value: "Dense Dropout Dense Dropout Dense" 
        - name: layersSizes 
          value: "64 0.5 64 0.5 1" 
        - name: layersActivations 
          value: "relu None relu None sigmoid" 
        - name: epochs 
          value: "3" 
        - name: batch_size 
          value: "128"
        - name: master_ip
          value: "http://3.143.228.222:5000" 
        command: ["python3"] 
        args: ["./docker_exec_file/runner.py"] 
      - name: experiment-two
        image: public.ecr.aws/q1b7b4u6/cedipengineering/docker_ml_ecr:latest
        ports:
        - containerPort: 80
        env:
        - name: MLFLOW_TRACKING_URI 
          value: "http://3.143.228.222:5000" 
        - name: experiment_name 
          value: mlflow_measurement_eks_8_exp
        - name: layersTypes 
          value: "Dense Dropout Dense Dropout Dense" 
        - name: layersSizes 
          value: "64 0.5 64 0.5 1" 
        - name: layersActivations 
          value: "relu None relu None sigmoid" 
        - name: epochs 
          value: "3" 
        - name: batch_size 
          value: "128"
        - name: master_ip
          value: "http://3.143.228.222:5000" 
        command: ["python3"] 
        args: ["./docker_exec_file/runner.py"] 
      - name: experiment-three
        image: public.ecr.aws/q1b7b4u6/cedipengineering/docker_ml_ecr:latest
        ports:
        - containerPort: 80
        env:
        - name: MLFLOW_TRACKING_URI 
          value: "http://3.143.228.222:5000" 
        - name: experiment_name 
          value: mlflow_measurement_eks_8_exp
        - name: layersTypes 
          value: "Dense Dropout Dense Dropout Dense" 
        - name: layersSizes 
          value: "64 0.5 64 0.5 1" 
        - name: layersActivations 
          value: "relu None relu None sigmoid" 
        - name: epochs 
          value: "3" 
        - name: batch_size 
          value: "128"
        - name: master_ip
          value: "http://3.143.228.222:5000" 
        command: ["python3"] 
        args: ["./docker_exec_file/runner.py"] 
      - name: experiment-four
        image: public.ecr.aws/q1b7b4u6/cedipengineering/docker_ml_ecr:latest
        ports:
        - containerPort: 80
        env:
        - name: MLFLOW_TRACKING_URI 
          value: "http://3.143.228.222:5000" 
        - name: experiment_name 
          value: mlflow_measurement_eks_8_exp
        - name: layersTypes 
          value: "Dense Dropout Dense Dropout Dense" 
        - name: layersSizes 
          value: "64 0.5 64 0.5 1" 
        - name: layersActivations 
          value: "relu None relu None sigmoid" 
        - name: epochs 
          value: "3" 
        - name: batch_size 
          value: "128"
        - name: master_ip
          value: "http://3.143.228.222:5000" 
        command: ["python3"] 
        args: ["./docker_exec_file/runner.py"] 
      - name: experiment-five
        image: public.ecr.aws/q1b7b4u6/cedipengineering/docker_ml_ecr:latest
        ports:
        - containerPort: 80
        env:
        - name: MLFLOW_TRACKING_URI 
          value: "http://3.143.228.222:5000" 
        - name: experiment_name 
          value: mlflow_measurement_eks_8_exp
        - name: layersTypes 
          value: "Dense Dropout Dense Dropout Dense" 
        - name: layersSizes 
          value: "64 0.5 64 0.5 1" 
        - name: layersActivations 
          value: "relu None relu None sigmoid" 
        - name: epochs 
          value: "3" 
        - name: batch_size 
          value: "128"
        - name: master_ip
          value: "http://3.143.228.222:5000" 
        command: ["python3"] 
        args: ["./docker_exec_file/runner.py"] 
      - name: experiment-six
        image: public.ecr.aws/q1b7b4u6/cedipengineering/docker_ml_ecr:latest
        ports:
        - containerPort: 80
        env:
        - name: MLFLOW_TRACKING_URI 
          value: "http://3.143.228.222:5000" 
        - name: experiment_name 
          value: mlflow_measurement_eks_8_exp
        - name: layersTypes 
          value: "Dense Dropout Dense Dropout Dense" 
        - name: layersSizes 
          value: "64 0.5 64 0.5 1" 
        - name: layersActivations 
          value: "relu None relu None sigmoid" 
        - name: epochs 
          value: "3" 
        - name: batch_size 
          value: "128"
        - name: master_ip
          value: "http://3.143.228.222:5000" 
        command: ["python3"] 
        args: ["./docker_exec_file/runner.py"] 
      - name: experiment-seven
        image: public.ecr.aws/q1b7b4u6/cedipengineering/docker_ml_ecr:latest
        ports:
        - containerPort: 80
        env:
        - name: MLFLOW_TRACKING_URI 
          value: "http://3.143.228.222:5000" 
        - name: experiment_name 
          value: mlflow_measurement_eks_8_exp
        - name: layersTypes 
          value: "Dense Dropout Dense Dropout Dense" 
        - name: layersSizes 
          value: "64 0.5 64 0.5 1" 
        - name: layersActivations 
          value: "relu None relu None sigmoid" 
        - name: epochs 
          value: "3" 
        - name: batch_size 
          value: "128"
        - name: master_ip
          value: "http://3.143.228.222:5000" 
        command: ["python3"] 
        args: ["./docker_exec_file/runner.py"] 
      - name: experiment-eight
        image: public.ecr.aws/q1b7b4u6/cedipengineering/docker_ml_ecr:latest
        ports:
        - containerPort: 80
        env:
        - name: MLFLOW_TRACKING_URI 
          value: "http://3.143.228.222:5000" 
        - name: experiment_name 
          value: mlflow_measurement_eks_8_exp
        - name: layersTypes 
          value: "Dense Dropout Dense Dropout Dense" 
        - name: layersSizes 
          value: "64 0.5 64 0.5 1" 
        - name: layersActivations 
          value: "relu None relu None sigmoid" 
        - name: epochs 
          value: "3" 
        - name: batch_size 
          value: "128"
        - name: master_ip
          value: "http://3.143.228.222:5000" 
        command: ["python3"] 
        args: ["./docker_exec_file/runner.py"] 
      restartPolicy: Never